name: ticker
version: 0.0.1

description: >-
  A package to work with Date & Time easily.
homepage: https://github.com/dart-lang/path

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: ^0.17.0

dev_dependencies:
  test: ^1.19.1
